# frozen_string_literal: true

namespace :view_component do
  namespace :css_manifest do
    desc "Ensure that an appropriately-named CSS file is within each sidecar."
    task add_missing_sidecar_css: :environment do
      components = Rails.root.join("app/components")

      sidecars = components.glob("*_component").select(&:directory?)

      sidecars.each do |sidecar_path|
        basename = "#{sidecar_path.basename}.css"

        css_path = sidecar_path.join(basename)

        next if css_path.exist?

        warn "Adding missing sidecar CSS: #{css_path.relative_path_from(Rails.root)}"

        css_path.open("w+") do |css|
          css.puts %[/* Add styles for this component */]
        end
      end
    end

    desc "Update the app/components/manifest.css manifest file with all sidecar CSS"
    task update: :environment do
      components = Rails.root.join("app/components")

      css_files = components.glob("*/**/*.css").reject { !_1.file? || _1.basename.fnmatch(".*") }

      manifest_path = components.join("manifest.css")

      manifest_path.open("w+") do |manifest|
        manifest.puts %[/* This file is auto-generated by ./bin/rails view_component:css_manifest:update */]
        manifest.puts %[/* Run that command whenever you add a new CSS file in ViewComponent */]
        manifest.puts

        css_files.each do |file|
          manifest.puts %[@import "./#{file.relative_path_from(components)}";]
        end
      end
    end
  end

  namespace :stimulus_manifest do
    desc "List the sidecar controllers that would be added to the manifest."
    task display: :environment do
      puts Stimulus::Manifest.generate_from(Rails.root.join("app/components"))
    end

    desc "Update the app/components/index.js stimulus manifest with all sidecar controllers"
    task update: :environment do
      manifest = Stimulus::Manifest.generate_from(Rails.root.join("app/components"))

      Rails.root.join("app/components/index.js").open("w+") do |index|
        index.puts %[// This file is auto-generated by ./bin/rails view_component:stimulus_manifest:update]
        index.puts %[// Run that command whenever you add a new controller in ViewComponent]
        index.puts
        index.puts %[import { application } from "../javascript/controllers/application";]
        index.puts manifest
      end
    end
  end

  namespace :assets do
    desc "Add missing and regenerate asset manifests."
    task regenerate: %i[view_component:css_manifest:add_missing_sidecar_css view_component:css_manifest:update view_component:stimulus_manifest:update] do
      warn "Assets regenerated."
    end
  end
end

if Rake::Task.task_defined?("stimulus:manifest:update")
  Rake::Task["stimulus:manifest:update"].enhance do
    Rake::Task["view_component:stimulus_manifest:update"].invoke
  end
end
