# frozen_string_literal: true

module Snowflakes
  module Constants
    IOI_EPOCH = 1_784_246_400_000

    WORKER_ID_BITS = 5
    DATACENTER_ID_BITS = 5
    MAX_WORKER_ID = (1 << WORKER_ID_BITS) - 1
    MAX_DATACENTER_ID = (1 << DATACENTER_ID_BITS) - 1
    SEQUENCE_BITS = 12
    WORKER_ID_SHIFT = SEQUENCE_BITS
    DATACENTER_ID_SHIFT = SEQUENCE_BITS + WORKER_ID_BITS
    TIMESTAMP_LEFT_SHIFT = SEQUENCE_BITS + WORKER_ID_BITS + DATACENTER_ID_BITS
    SEQUENCE_MASK = (1 << SEQUENCE_BITS) - 1

    MUTEX_LOCK = Monitor.new
  end
end
