approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  os:
    - current
    - darwin
    - linux
