// This file is auto-generated by ./bin/rails view_component:stimulus_manifest:update
// Run that command whenever you add a new controller in ViewComponent

import { application } from "../javascript/controllers/application";
import ComparisonComponent__ComparisonComponentController from "./comparison_component/comparison_component_controller";
import ComparisonItemComponent__ComparisonItemComponentController from "./comparison_item_component/comparison_item_component_controller";
import ComparisonToggleComponent__ComparisonToggleComponentController from "./comparison_toggle_component/comparison_toggle_component_controller";
import FlashMessageComponent__FlashMessageComponentController from "./flash_message_component/flash_message_component_controller";
import FlashMessagesComponent__FlashMessagesComponentController from "./flash_messages_component/flash_messages_component_controller";
import FooterComponent__FooterComponentController from "./footer_component/footer_component_controller";
import HeaderComponent__HeaderComponentController from "./header_component/header_component_controller";
import HomePageComponent__HomePageComponentController from "./home_page_component/home_page_component_controller";
import ImplementationComponent__ImplementationComponentController from "./implementation_component/implementation_component_controller";
import ImplementationDetailComponent__ImplementationDetailComponentController from "./implementation_detail_component/implementation_detail_component_controller";
import SolutionComponent__SolutionComponentController from "./solution_component/solution_component_controller";
import SolutionDetailsComponent__SolutionDetailsComponentController from "./solution_details_component/solution_details_component_controller";
import SolutionFiltersComponent__SolutionFiltersComponentController from "./solution_filters_component/solution_filters_component_controller";
import SolutionSortComponent__SolutionSortComponentController from "./solution_sort_component/solution_sort_component_controller";
import SolutionsComponent__SolutionsComponentController from "./solutions_component/solutions_component_controller";
import TagComponent__TagComponentController from "./tag_component/tag_component_controller";
import TagListComponent__TagListComponentController from "./tag_list_component/tag_list_component_controller";

application.register("comparison-component--comparison-component", ComparisonComponent__ComparisonComponentController);
application.register("comparison-item-component--comparison-item-component", ComparisonItemComponent__ComparisonItemComponentController);
application.register("comparison-toggle-component--comparison-toggle-component", ComparisonToggleComponent__ComparisonToggleComponentController);
application.register("flash-message-component--flash-message-component", FlashMessageComponent__FlashMessageComponentController);
application.register("flash-messages-component--flash-messages-component", FlashMessagesComponent__FlashMessagesComponentController);
application.register("footer-component--footer-component", FooterComponent__FooterComponentController);
application.register("header-component--header-component", HeaderComponent__HeaderComponentController);
application.register("home-page-component--home-page-component", HomePageComponent__HomePageComponentController);
application.register("implementation-component--implementation-component", ImplementationComponent__ImplementationComponentController);
application.register("implementation-detail-component--implementation-detail-component", ImplementationDetailComponent__ImplementationDetailComponentController);
application.register("solution-component--solution-component", SolutionComponent__SolutionComponentController);
application.register("solution-details-component--solution-details-component", SolutionDetailsComponent__SolutionDetailsComponentController);
application.register("solution-filters-component--solution-filters-component", SolutionFiltersComponent__SolutionFiltersComponentController);
application.register("solution-sort-component--solution-sort-component", SolutionSortComponent__SolutionSortComponentController);
application.register("solutions-component--solutions-component", SolutionsComponent__SolutionsComponentController);
application.register("tag-component--tag-component", TagComponent__TagComponentController);
application.register("tag-list-component--tag-list-component", TagListComponent__TagListComponentController);
