default: &default
  origin: "no-reply@investinopen.org"
  address: ""
  external: false
  port: 587
  password: ""
  username: ""

development:
  <<: *default
  address: "mailcatcher"
  external: false
  port: 1025

test:
  <<: *default

staging:
  <<: *default
  address: "smtp.sendgrid.net"
  external: true
  origin: "no-reply@investinopen.org"
  port: 587
  username: apikey

production:
  <<: *default
  address: "smtp.sendgrid.net"
  external: true
  origin: "no-reply@investinopen.org"
  port: 587
  username: apikey
