# frozen_string_literal: true

module SolutionProperties
  module Schemas
    # dry-types and schemas for working with inputs against a {SolutionIntake} / intake-type record.
    #
    # @see ::SolutionIntake
    module Intake
      # Used by {ATTR_REMAP} in order map nested attributes,
      # as well as any attribute aliases.
      # @return [{ Symbol => Symbol }]
      ATTR_MAPPING = {
        access_conditions: :access_condition_ids,
        authentication_standards: :authentication_standard_ids,
        board_level: :board_level_id,
        board_structures: :board_structure_ids,
        business_forms: :business_form_ids,
        bylaws: :bylaws_attributes,
        code_license: :code_license_attributes,
        code_of_conduct: :code_of_conduct_attributes,
        code_repository: :code_repository_attributes,
        community_engagement: :community_engagement_attributes,
        community_engagement_activities: :community_engagement_activity_ids,
        community_governances: :community_governance_ids,
        content_licenses: :content_license_ids,
        contribution_pathways: :contribution_pathways_attributes,
        current_affiliations: :current_affiliations_attributes,
        domain_relevances: :domain_relevance_ids,
        equity_and_inclusion: :equity_and_inclusion_attributes,
        financial_reporting_level: :financial_reporting_level_id,
        founding_institutions: :founding_institutions_attributes,
        governance_records: :governance_records_attributes,
        governance_structure: :governance_structure_attributes,
        hosting_strategy: :hosting_strategy_id,
        integrations: :integration_ids,
        licenses: :license_ids,
        maintenance_status: :maintenance_status_id,
        metadata_standards: :metadata_standard_ids,
        metrics_standards: :metrics_standard_ids,
        nonprofit_status: :nonprofit_status_id,
        open_api: :open_api_attributes,
        open_data: :open_data_attributes,
        persistent_identifier_standards: :persistent_identifier_standard_ids,
        preservation_standards: :preservation_standard_ids,
        pricing: :pricing_attributes,
        primary_funding_sources: :primary_funding_source_ids,
        privacy_policy: :privacy_policy_attributes,
        product_roadmap: :product_roadmap_attributes,
        programming_languages: :programming_language_ids,
        readiness_level: :readiness_level_id,
        recent_grants: :recent_grants_attributes,
        registries: :registries_attributes,
        revenue_sources: :revenue_source_ids,
        security_standards: :security_standard_ids,
        service_providers: :service_providers_attributes,
        solution_categories: :solution_category_ids,
        staffing_full_time: :staffing_full_time_id,
        staffing_volunteer: :staffing_volunteer_id,
        status_certifications: :status_certification_ids,
        top_granting_institutions: :top_granting_institutions_attributes,
        user_contributions: :user_contribution_ids,
        user_documentation: :user_documentation_attributes,
        values_frameworks: :values_framework_ids,
        web_accessibility: :web_accessibility_attributes,
        web_accessibility_applicabilities: :web_accessibility_applicability_ids,
      }.freeze

      # A proc suitable for use with `with_key_transform`.
      #
      # @see ATTR_MAPPING
      # @return [Proc]
      ATTR_REMAP = ->(key) do
        key = key.to_sym

        ATTR_MAPPING.fetch(key, key)
      end

      # A hash schema matching the known, settable properties of a {SolutionIntake}.
      # @return [Dry::Types::Hash{Symbol => Object}]
      Params = ::Inputs::Types::BaseSchema.schema(
        access_condition_ids?: ::Inputs::Types::Attributes::IDs,
        annual_expenses?: ::Inputs::Types::Attributes::Money,
        annual_revenue?: ::Inputs::Types::Attributes::Money,
        authentication_standard_ids?: ::Inputs::Types::Attributes::IDs,
        authentication_standard_other?: ::Inputs::Types::Attributes::String,
        board_level_id?: ::Inputs::Types::Attributes::ID,
        board_level_other?: ::Inputs::Types::Attributes::String,
        board_members_url?: ::Inputs::Types::Attributes::String,
        board_structure_ids?: ::Inputs::Types::Attributes::IDs,
        board_structure_other?: ::Inputs::Types::Attributes::String,
        business_form_ids?: ::Inputs::Types::Attributes::IDs,
        business_form_other?: ::Inputs::Types::Attributes::String,
        bylaws_attributes?: ::Implementations::Schemas::Bylaws::Type,
        bylaws_implementation?: ::Inputs::Types::Enums::ImplementationStatus,
        code_license_attributes?: ::Implementations::Schemas::CodeLicense::Type,
        code_license_implementation?: ::Inputs::Types::Enums::ImplementationStatus,
        code_of_conduct_attributes?: ::Implementations::Schemas::CodeOfConduct::Type,
        code_of_conduct_implementation?: ::Inputs::Types::Enums::ImplementationStatus,
        code_repository_attributes?: ::Implementations::Schemas::CodeRepository::Type,
        code_repository_implementation?: ::Inputs::Types::Enums::ImplementationStatus,
        community_engagement_activity_ids?: ::Inputs::Types::Attributes::IDs,
        community_engagement_activity_other?: ::Inputs::Types::Attributes::String,
        community_engagement_attributes?: ::Implementations::Schemas::CommunityEngagement::Type,
        community_engagement_implementation?: ::Inputs::Types::Enums::ImplementationStatus,
        community_governance_ids?: ::Inputs::Types::Attributes::IDs,
        contact?: ::Inputs::Types::Attributes::String,
        content_license_ids?: ::Inputs::Types::Attributes::IDs,
        content_license_other?: ::Inputs::Types::Attributes::String,
        contribution_pathways_attributes?: ::Implementations::Schemas::ContributionPathways::Type,
        contribution_pathways_implementation?: ::Inputs::Types::Enums::ImplementationStatus,
        country_code?: ::Inputs::Types::Enums::Countries,
        currency?: ::Inputs::Types::Enums::Currencies,
        current_affiliation_free_input?: ::Inputs::Types::Attributes::String,
        current_affiliations_attributes?: ::Structured::Schemas::Institution::List,
        domain_relevance_ids?: ::Inputs::Types::Attributes::IDs,
        email?: ::Inputs::Types::Attributes::String,
        equity_and_inclusion_attributes?: ::Implementations::Schemas::EquityAndInclusion::Type,
        equity_and_inclusion_implementation?: ::Inputs::Types::Enums::ImplementationStatus,
        financial_date_range?: ::Inputs::Types::Attributes::String,
        financial_numbers_documented_url?: ::Inputs::Types::Attributes::String,
        financial_numbers_publishability?: ::Inputs::Types::Enums::FinancialNumbersPublishability,
        financial_reporting_level_id?: ::Inputs::Types::Attributes::ID,
        financial_reporting_level_other?: ::Inputs::Types::Attributes::String,
        first_name?: ::Inputs::Types::Attributes::String,
        fiscal_host?: ::Inputs::Types::Attributes::String,
        founded_on?: ::Inputs::Types::Attributes::Date,
        founding_institution_free_input?: ::Inputs::Types::Attributes::String,
        founding_institutions_attributes?: ::Structured::Schemas::Institution::List,
        funding_needs?: ::Inputs::Types::Attributes::String,
        governance_records_attributes?: ::Implementations::Schemas::GovernanceRecords::Type,
        governance_records_implementation?: ::Inputs::Types::Enums::ImplementationStatus,
        governance_structure_attributes?: ::Implementations::Schemas::GovernanceStructure::Type,
        governance_structure_implementation?: ::Inputs::Types::Enums::ImplementationStatus,
        governance_summary?: ::Inputs::Types::Attributes::String,
        hosting_strategy_id?: ::Inputs::Types::Attributes::ID,
        integration_ids?: ::Inputs::Types::Attributes::IDs,
        integration_other?: ::Inputs::Types::Attributes::String,
        investment_income?: ::Inputs::Types::Attributes::Money,
        key_achievements?: ::Inputs::Types::Attributes::String,
        last_name?: ::Inputs::Types::Attributes::String,
        launch_year?: ::Inputs::Types::Attributes::Integer,
        license_ids?: ::Inputs::Types::Attributes::IDs,
        license_other?: ::Inputs::Types::Attributes::String,
        logo?: ::Inputs::Types::Any,
        logo_remote_url?: ::Inputs::Types::Attributes::String,
        maintenance_status_id?: ::Inputs::Types::Attributes::ID,
        member_count?: ::Inputs::Types::Attributes::Integer,
        membership_program_url?: ::Inputs::Types::Attributes::String,
        metadata_standard_ids?: ::Inputs::Types::Attributes::IDs,
        metadata_standard_other?: ::Inputs::Types::Attributes::String,
        metrics_standard_ids?: ::Inputs::Types::Attributes::IDs,
        metrics_standard_other?: ::Inputs::Types::Attributes::String,
        mission?: ::Inputs::Types::Attributes::String,
        name?: ::Inputs::Types::Attributes::String,
        nonprofit_status_id?: ::Inputs::Types::Attributes::ID,
        open_api_attributes?: ::Implementations::Schemas::OpenAPI::Type,
        open_api_implementation?: ::Inputs::Types::Enums::ImplementationStatus,
        open_data_attributes?: ::Implementations::Schemas::OpenData::Type,
        open_data_implementation?: ::Inputs::Types::Enums::ImplementationStatus,
        organizational_history?: ::Inputs::Types::Attributes::String,
        other_revenue?: ::Inputs::Types::Attributes::Money,
        persistent_identifier_standard_ids?: ::Inputs::Types::Attributes::IDs,
        persistent_identifier_standard_other?: ::Inputs::Types::Attributes::String,
        preservation_standard_ids?: ::Inputs::Types::Attributes::IDs,
        preservation_standard_other?: ::Inputs::Types::Attributes::String,
        pricing_attributes?: ::Implementations::Schemas::Pricing::Type,
        pricing_implementation?: ::Inputs::Types::Enums::PricingImplementationStatus,
        primary_funding_source_ids?: ::Inputs::Types::Attributes::IDs,
        primary_funding_source_other?: ::Inputs::Types::Attributes::String,
        privacy_policy_attributes?: ::Implementations::Schemas::PrivacyPolicy::Type,
        privacy_policy_implementation?: ::Inputs::Types::Enums::ImplementationStatus,
        product_roadmap_attributes?: ::Implementations::Schemas::ProductRoadmap::Type,
        product_roadmap_implementation?: ::Inputs::Types::Enums::ImplementationStatus,
        program_revenue?: ::Inputs::Types::Attributes::Money,
        programming_language_ids?: ::Inputs::Types::Attributes::IDs,
        programming_language_other?: ::Inputs::Types::Attributes::String,
        readiness_level_id?: ::Inputs::Types::Attributes::ID,
        recent_grant_free_input?: ::Inputs::Types::Attributes::String,
        recent_grants_attributes?: ::Structured::Schemas::Grant::List,
        registries_attributes?: ::Structured::Schemas::Registry::List,
        registry_free_input?: ::Inputs::Types::Attributes::String,
        research_organization_registry_url?: ::Inputs::Types::Attributes::String,
        revenue_source_ids?: ::Inputs::Types::Attributes::IDs,
        revenue_source_other?: ::Inputs::Types::Attributes::String,
        scoss?: ::Inputs::Types::Attributes::Bool,
        security_standard_ids?: ::Inputs::Types::Attributes::IDs,
        security_standard_other?: ::Inputs::Types::Attributes::String,
        service_provider_free_input?: ::Inputs::Types::Attributes::String,
        service_providers_attributes?: ::Structured::Schemas::ServiceProvider::List,
        service_summary?: ::Inputs::Types::Attributes::String,
        shareholders?: ::Inputs::Types::Attributes::Bool,
        solution_category_ids?: ::Inputs::Types::Attributes::IDs,
        staffing_full_time_id?: ::Inputs::Types::Attributes::ID,
        staffing_volunteer_id?: ::Inputs::Types::Attributes::ID,
        status_certification_ids?: ::Inputs::Types::Attributes::IDs,
        top_granting_institution_free_input?: ::Inputs::Types::Attributes::String,
        top_granting_institutions_attributes?: ::Structured::Schemas::Institution::List,
        total_assets?: ::Inputs::Types::Attributes::Money,
        total_contributions?: ::Inputs::Types::Attributes::Money,
        total_liabilities?: ::Inputs::Types::Attributes::Money,
        user_contribution_ids?: ::Inputs::Types::Attributes::IDs,
        user_contribution_other?: ::Inputs::Types::Attributes::String,
        user_documentation_attributes?: ::Implementations::Schemas::UserDocumentation::Type,
        user_documentation_implementation?: ::Inputs::Types::Enums::ImplementationStatus,
        values_framework_ids?: ::Inputs::Types::Attributes::IDs,
        web_accessibility_applicability_ids?: ::Inputs::Types::Attributes::IDs,
        web_accessibility_attributes?: ::Implementations::Schemas::WebAccessibility::Type,
        web_accessibility_implementation?: ::Inputs::Types::Enums::ImplementationStatus,
        website?: ::Inputs::Types::Attributes::String,
      ).with_key_transform(&ATTR_REMAP)
    end
  end
end
