name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

env:
  DATABASE_URL: "postgres://postgres:postgres@localhost:5432/rails_test"
  PATH: /usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:/usr/local/sbin
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  REDIS_URL: redis://localhost:6379
  RUBYOPT: "-W:no-deprecated -W:no-experimental"

jobs:
  erblint:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest
    steps:
      - name: "Install Dependent libraries"
        run: |
          sudo apt-get update
          sudo apt-get -yqq install libpq-dev libvips libvips-dev

      - name: "Checkout code"
        uses: actions/checkout@v1

      - name: "Install Ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: "Run ERBLint"
        env:
          RAILS_ENV: development
        run: |
          bin/erblint --config .erb-lint.yml .

  rubocop:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest
    steps:
      - name: "Install Dependent libraries"
        run: |
          sudo apt-get update
          sudo apt-get -yqq install libpq-dev libvips libvips-dev

      - name: "Checkout code"
        uses: actions/checkout@v1

      - name: "Install Ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: "Run Rubocop"
        env:
          RAILS_ENV: development
        run: |
          bin/rubocop

  rspec:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.1-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: rails_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports: ["6379:6379"]
        options: --entrypoint redis-server

    steps:
      - name: "Install Dependent libraries"
        run: |
          sudo apt-get update
          sudo apt-get -yqq install libpq-dev libvips libvips-dev

      - name: "Checkout code"
        uses: actions/checkout@v1

      - name: "Install Ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: corepack enable

      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          check-latest: false
          cache: "yarn"
          cache-dependency-path: yarn.lock
          node-version-file: ".node-version"

      - run: yarn install --immutable

      - name: "Set up DB"
        run: |
          bin/rails db:create
          bin/rails db:migrate

      - name: "Build assets"
        run: |
          bin/rails assets:precompile

      - name: "Run API specs"
        run: |
          bin/rspec
